# Generated by Django 5.0 on 2024-01-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_product',
            name='quantity',
            field=models.IntegerField(default=2),
        ),
    ]
