# Generated by Django 4.2.7 on 2024-01-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_buyer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.product_category'),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.seller'),
        ),
    ]
